### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Alpha-Like** [GPSxtreme/melomix#1]
Make an offline player in which we can import mp3 files!

Nd am ur classmate🗿

**Comment by GPSxtreme** [comment]
Hey,
The feature is already present in melomix.
You need to provide storage permissions to access locally saved songs.(Asked by default when installed)

**Comment by Alpha-Like** [comment]
> Hey,
> The feature is already present in melomix.
> You need to provide storage permissions to access locally saved songs.(Asked by default when installed)

Fine bro! 

It's me 18!
